# Generated by Django 4.2.3 on 2024-03-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='color',
        ),
    ]
