# Generated by Django 4.2.3 on 2024-03-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_remove_recipe_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='desc',
            new_name='description',
        ),
    ]
